using System;
using Apps.Communication.Core;

namespace School.People.App.Events
{
    public abstract class Event<T> : Event, IEvent<T>
    {
        /// <summary>
        /// Data generated by/for this event.
        /// </summary>
        public T Data { get; }

        /// <summary>
        /// Creates a new event.
        /// </summary>
        /// <param name="id">The event identifier.</param>
        /// <param name="data">Data exposed to event handlers.</param>
        protected Event(Guid id, T data)
            : base(id) { Data = data; }
    }

    public abstract class Event : IEvent
    {
        /// <summary>
        /// The event's identifier. 
        /// This usually corresponds to the identifier of 
        /// <see cref="ICommand"/> that propagated the event.
        /// </summary>
        public Guid Id { get; }

        protected Event(Guid id)
        {
            Id = id;
        }
    }
}
